services:
  - type: web
    name: jap-frontend
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://jap-backend-qcmz.onrender.com/api # Replace with your actual backend URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
